### ISSUE TITLE
Readme does not specify the SDK is a UWP app

### ISSUE THREAD

**Issue by hexate** [TapWithUs/tap-standalonewin-sdk#1]
I tried loading up this project, and the SDK could not find a missing reference to UWP libraries, since my dev environment was not configured for UWP dev. Updating VS for UWP fixed it, but somewhere in the Readme making this clear would be helpful.

**Comment by ilouzl** [comment]
Thanks for the comment,  It's was added at https://github.com/TapWithUs/tap-standalonewin-sdk/commit/2b6705c3016857d02937a7cf0bf1e5bf48ae2a59

**Comment by yunho-c** [comment]
I am encountering issues with initial compilation even after referencing 'windows.winmd' from Windows SDK (as stated in updated docs). So checking the "UWP Development Environment" box while installing VS resolves it, yes?

**Comment by yunho-c** [comment]
> 
> 
> I am encountering issues with initial compilation even after referencing 'windows.winmd' from Windows SDK (as stated in updated docs). So checking the "UWP Development Environment" box while installing VS resolves it, yes?

Installing 10.0.17763.0 version of Windows SDK resolved the compilation errors.
